files: ^code/Outil-prevision/
default_stages: [commit, push]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: check-merge-conflict
      #- id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "120"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # - repo: https://github.com/pycqa/pylint
  #   rev: v2.15.4
  #   hooks:
  #     - id: pylint
  #       args:
  #       - --max-line-length=120
  #       - -d duplicate-code
  #       - --disable=W0511
  #       - --disable=missing-docstring,invalid-name,import-error,duplicate-code,invalid-sequence-index
  #       - --disable=C0413 # wrong-import-position import positions are handled by isort
  #       # - --fail-under=5
