
# MODEL META UB - LGBM - PDV
config_lgbm:
  TARGET: FRAUD_FLAG
  WEIGHT: WEIGHT
  FEATURES:
    - 'COMPUTERS'
    - 'TELEPHONES FAX MACHINES TWOWAY RADIOS'
    - 'AUDIO ACCESSORIES'
    - 'COMPUTER PERIPHERALS ACCESSORIES'
    - 'TELEVISIONS HOME CINEMA'
    - 'BABY EQUIPMENT'
    - 'TABLEWARE'
    - 'BED LINEN'
    - 'DECORATIVE ACCESSORIES'
    - 'LIGHTING'
    - 'SOFT FURNISHINGS'
    - 'KITCHEN UTENSILS GADGETS'
    - 'STORAGE ORGANISATION'
    - 'IMAGING EQUIPMENT'
    - 'BATH LINEN'
    - 'POWER BATTERIES'
    - 'MEN S CLOTHES'
    - 'LAUNDRY CLOTHESCARE'
    - 'HOUSEHOLD CLEANING'
    - 'LIVING DINING FURNITURE'
    - 'LUGGAGE'
    - 'COOKWARE'
    - 'BATHROOM ACCESSORIES'
    - 'HIFI'
    - 'APPLE' 
    - 'RETAILER' 
    - 'SAMSUNG' 
    - 'LG' 
    - 'BUGABOO' 
    - 'LE CREUSET' 
    - 'OXO' 
    - 'MAXICOSI' 
    - 'SONY' 
    - 'SILVER CROSS' 
    - 'ANYDAY RETAILER' 
    - 'SKANDINAVISK' 
    - 'PANASONIC' 
    - 'PHILIPS' 
    - 'ROBERT WELCH' 
    - 'WEST ELM' 
    - 'LSA INTERNATIONAL'
    - 'CASH_MEAN' 
    - 'CASH_STD' 
    - 'CASH_MIN' 
    - 'CASH_MAX' 
    - 'CASH_TOTAL'
    - NB_OF_ITEMS
    - GOODSCODE
    - NBR_OF_PROD_PURCHAS
    - AIRPODS
    - WATCH
    - IPAD
    - IPHONE
    - MACBOOK
    - GALAXY
    - SAMSUNG_QLED
    - TOTAL_APPLE
  categorical_features:
    - GOODSCODE
  seed: 5432
  n_splits: 5
  parameters:
    objective: binary
    metric: binary_logloss
    max_depth: 6
    min_data_in_leaf: 10
    colsample_bytree: 0.85
    subsample: 0.85
    learning_rate: 0.007
    num_iteration: 2000
    lambda_l1 : 1
    n_jobs: -1
    verbose : -1
